name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configure
      run: |
          git submodule update --init --recursive
          mkdir -p build
          cd build
          cmake ..

    - name: Build
      run: |
          cd build
          make

    - name: Run tests
      run: |
          cd build
          ctest --output-on-failure
  build_container:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Singularity
        run: |
          export DEBIAN_FRONTEND=noninteractive
          export TZ=Europe/Rome

          echo "tzdata tzdata/Areas select Europe"         | sudo debconf-set-selections
          echo "tzdata tzdata/Zones/Europe select Rome"   | sudo debconf-set-selections

          sudo -E apt-get update
          sudo -E apt-get install -y tzdata

          sudo -E apt-get install -y singularity-container

      - name: Build Singularity container image
        run: |
          sudo singularity build image_to_grayscale.sif singularity.def

      - uses: actions/upload-artifact@v4
        with:
          name: singularity-image
          path: image_to_grayscale.sif
  
  send_to_cluster:
    needs: build_container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: singularity-image
          path: ./

      - name: Install expect
        run: sudo apt-get update && sudo apt-get install -y expect

      - name: Send files and Sbatch job
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_PASSPHRASE: ${{ secrets.SSH_PASSPHRASE }}
        run: |
          mkdir -p ~/.ssh
          
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | base64 -d > ~/.ssh/my_key
          echo "${{ secrets.SSH_PUBLIC_KEY }}"  | base64 -d > ~/.ssh/my_key.pub
          echo "${{ secrets.SSH_CERT }}"        | base64 -d > ~/.ssh/my_key-cert.pub

          chmod 600 ~/.ssh/my_key
          chmod 644 ~/.ssh/my_key.pub ~/.ssh/my_key-cert.pub

          eval "$(ssh-agent -s)"

          expect <<EOF
          spawn ssh-add "$HOME/.ssh/my_key"
          expect "Enter passphrase for $HOME/.ssh/my_key:"
          send "$SSH_PASSPHRASE\r"
          expect eof
          EOF

          ssh -i ~/.ssh/my_key -o StrictHostKeyChecking=no msandret@login.g100.cineca.it "mkdir -p ~/jobs/img_to_grayscale_automatic"
          scp -i ~/.ssh/my_key -o StrictHostKeyChecking=no galileo100/job.sh msandret@login.g100.cineca.it:~/jobs/img_to_grayscale_automatic/
          scp -i ~/.ssh/my_key -o StrictHostKeyChecking=no -r galileo100/input_images msandret@login.g100.cineca.it:~/jobs/img_to_grayscale_automatic/
          scp -i ~/.ssh/my_key -o StrictHostKeyChecking=no image_to_grayscale.sif msandret@login.g100.cineca.it:~/jobs/img_to_grayscale_automatic/
          ssh -i ~/.ssh/my_key -o StrictHostKeyChecking=no msandret@login.g100.cineca.it "sbatch ~/jobs/img_to_grayscale_automatic/job.sh"
          ssh -i ~/.ssh/my_key -o StrictHostKeyChecking=no msandret@login.g100.cineca.it "squeue -u msandret"