name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Configure
      run: |
          git submodule update --init --recursive
          mkdir -p build
          cd build
          cmake ..

    - name: Build
      run: |
          cd build
          make

    - name: Run tests
      run: |
          cd build
          ctest --output-on-failure
  build_container:
    needs: build_and_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Singularity
        run: |
          sudo apt-get update
          sudo apt-get install -y singularity-container
          echo "root:100000:65536" | sudo tee -a /etc/subuid /etc/subgid

      - name: Build Singularity container image
        run: |
          sudo singularity build --fakeroot image_to_grayscale.sif singularity.def

      - uses: actions/upload-artifact@v4
        with:
          name: singularity-image
          path: image_to_grayscale.sif